# Book settings for myrust.dev
# A learning resource for Python/C++ developers transitioning to Rust

title: "MyRust.dev"
author: "MyRust.dev"
logo: logo.svg

# Execution settings
execute:
  execute_notebooks: force
  timeout: 300

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: myrust-dev-guide.tex

# Website configuration
repository:
  url: https://github.com/yourusername/myrust.dev  # Update with your actual repo
  path_to_book: .  # Book is at repository root
  branch: main

# HTML theme and features
html:
  use_issues_button: false
  use_repository_button: true
  use_edit_page_button: true
  use_download_button: false
  home_page_in_navbar: true
  navbar_number_sections: false
  show_navbar_depth: 2
  extra_footer: "<p>© 2025 MyRust.dev - A learning resource for developers transitioning to Rust</p>"
  google_analytics_id: ""  # Add your GA ID when ready

# Search functionality
search:
  search_index_only: false

# Parse and render settings
parse:
  myst_enable_extensions:
    - colon_fence
    - deflist
    - dollarmath
    - fieldlist
    - html_admonition
    - html_image
    - linkify
    - replacements
    - smartquotes
    - substitution
    - tasklist

# Sphinx settings
sphinx:
  config:
    html_show_copyright: false
    html_last_updated_fmt: "%b %d, %Y"
    language: en
